### ISSUE TITLE
Classic theme fallback

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpacks#1]
Line 161 of textpacks - does Classic theme get used as a fallback now as of v4.6? Need to confirm this. Maybe change to 'The default theme will be used as a fallback.' would cover us in this instance.

**Comment by petecooper** [comment]
On the grounds that Hive is front and centre with 4.6, and all Textpacks have the string present (but not translated), this can probably be closed now.

/cc @Bloke @philwareham

**Comment by philwareham** [comment]
Agreed. Will close.
