### ISSUE TITLE
Base initial work on 4.5.x rather than 4.6.0

### ISSUE THREAD

**Issue by gocom** [textpattern/textpacks#10]
Base initial work on 4.5.x rather than 4.6.0. Once the base is compatible with 4.5.x, branch to 4.5-dev, and update the master for 4.6.0.

This so that we can serve the translations from the repository to older Textpattern installations using [textpattern/rpc](https://github.com/textpattern/rpc) server.

**Comment by philwareham** [comment]
Don't need to keep this open - I make sure the RPC is up-to-date anyway.
