### ISSUE TITLE
Wrap `tag_css` in code

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#104]
The `tag_css` entry, currently line 1125, provides the ability to have a CSS link built for the HTML `head`. With that in mind, should the head reference be wrapped in code tags? If so, should `head` be adapted to say `<head>` instead? It makes it less ambiguous.

**Comment by philwareham** [comment]
Yes, I think so.

In documentation repo whenever a HTML tag is referenced I've always put the enclosing around it - so l;et's be consistent.

**Comment by petecooper** [comment]
Right on. OK, I will deal.

**Comment by petecooper** [comment]
Addressed by https://github.com/textpattern/textpacks/commit/debb35869697178303e7d11b0259792435d6b43f
