### ISSUE TITLE
Handling strings from 4.7.0+

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpacks#109]
In addition to Issue #5, which is definitely something we should look into if only to save translation effort (no point translating unused strings), there's the question of how to actually manage languages going forward.

Options and things to consider, not exclusive as some may be used in combination:
1. Bundle `en-gb` with the download as we do now, with strings only from that release present (+ common/public ones that are useful to plugins, even if not explicitly used in the admin side).
2. Bundle all Textpacks with the download, increasing the size of the package considerably. Possibly with all unneeded strings removed, as above.
3. Remove 'install from server' option if all Textpacks are bundled with the download. Installing a new language will be done from File.
4. If only `en-gb` bundled, installing a new language could first check the local directory for a matching pack and, if not present, would request one from the RPC server for that language and that Txp version, then store it in the lang directory and install from there.
5. Maintain multiple versions of each lang file on the server tagged somehow with the version of Txp to which they relate.
6. Maintain a dev version that will become the new version upon release so that beta testers can get strings.
7. Or maintain a single master (database?) that has all strings in it, and have two additional columns such as `version_introduced` and `version_revoked`. Installation could then be via an API that generates a list of strings for a specific Txp version. Note that this doesn't mean we necessarily build string packs like we do now, on demand for users to install (though we could do that), but could use it internally to bundle files for release. Essentially, it'd be the same as we have now in terms of a central repo for all strings, but the additional columns allow specific packs to be generated for a particular version.
8. Consider how to clean up old strings in people's installations. This will help with site speed, as downloading strings on each page load is expensive.
9. Rearrange the system so it doesn't use the database for strings but looks them up from file. Perhaps convert to an `.ini` file structure with `[group]` headings. That would permit us to use PHP's [parse_ini_file](http://php.net/manual/en/function.parse-ini-file.php) to grab a subset. Note that all strings can be loaded in one hit and the same `$textarray` structure can be maintained as now so `gTxt()` continues to work, it just saves a DB call. Rewriting the `load_lang()` API call could read the entire file and just return the given `[sections]` as an array, to mimic what we do today. The downside is that's not the same as our internal Textpack format. And I don't know how efficient `parse_ini_file()` is (probably not very). Alternatively, do the same file-based system but use our Textpack format as the basis and pluck named sections out of that.
10. Note to self: write an `smd_` plugin for string management and Textpack generation for sharing purposes, or coerce someone else into writing one. NOT a core feature as it's not a day-to-day activity for clients.

More options exist, I'm sure. The big question is which way to jump. Please discuss the relative merits of various avenues of exploration and let's choose a suitable path.

**Comment by rwetzlmayr** [comment]
> Consider how to clean up old strings in people's installations. This will help with site speed, as downloading strings on each page load is expensive.

On my development system, the ```load_lang()```call from the **Content > Write** panel incurs for an inclusive cost of circa 5% of the total runtime. It loads strings for all events there but since we have an index on ```(lang, event)``` this cost wouldn't be very different on the public side.  My measurements are sort of anecdotal evidence as collected by a fews runs w/ XDebug's profiler.

>  Rearrange the system so it doesn't use the database for strings but looks them up from file. Perhaps convert to an .ini file structure with [group] headings. That would permit us to use PHP's parse_ini_file to grab a subset.

I'd suggest to consider a generated .php file which contains (a collection of) string array(s). PHP has an efficient parser for .php files and various caching solutions ;-)

**Comment by philwareham** [comment]
I can re-look at issue #5 and remove strings that are definitely not used - maybe move them to a 'deprecated' folder for now so they aren't totally gone?

Would that help a little? The programming stuff is obviously down to you guys.

**Comment by philwareham** [comment]
Changed issue title - bundling of Textpacks is targeted at v4.7 now.

**Comment by philwareham** [comment]
Pretty sure this issue can be closed now. Textpacks are handled much more efficiently in Textpattern 4.7 (languages branch, which will soon be merged into dev branch).

One question remains over cleaning up old strings from a database inherited from previous Textpattern installs (point 8 above). Maybe open an issue for that at the Textpattern repo if you feel it's worth investigating?
