### ISSUE TITLE
`rel` string in `#@tag`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#112]
There's a string called `rel` in `#@tag` - line 1080 currently - and in English it's `Rel HTML attribute`. 

It needs to be made more obvious that it's code. Before I make changes, I wanted an extra pair of eyes to confirm what I'm about to do is not stupidity:

* lowercase the `Rel`
* add `<code>` around the newly-lowercased `rel`

If that's OK, then I want to do the same with `html_id` in `#@tag` on line 1053 currently - again, make it obviously code and not explanatory text.

@philwareham - you're on point with this kind of thing, what do you think?

**Comment by philwareham** [comment]
Agreed. There is also line 1053 (html_id) and line 1068 (media) that should also done, I think.

**Comment by petecooper** [comment]
Done.
