### ISSUE TITLE
Preferences: some label changes

### ISSUE THREAD

**Issue by wion** [textpattern/textpacks#114]
Using 4.6 layout for DOM reference...

### Site region

1) DST

* Automatically adjust DST setting? 
* DST enabled?

Bloke will reverse the order on those for sake of logic, then the labels should be changed to:

* Daylight Savings Time (DST) enabled?
* Automatically adjust DST?

2) URLs

* Permanent link mode

The use of "mode" makes it seem like an “On/Off” situation (is mode on? mode off?). And "permanent link" isn't even accurate; we're talking about URLs, whether they're linked or not. I'd recommend

* "URL pattern

### Publish region

1) Excerpts

* Articles use excerpts?

You want to put the principle noun first to give it weight. So better like this:

* Use excerpts on articles?

2) Permalink titles

* Permalink title-like-this (instead of TitleLikeThis)?" 

A bit awkward. This would actually be better as a radio button, with [the text strings shown here](http://forum.textpattern.com/viewtopic.php?pid=295299#p295299).

**Comment by rwetzlmayr** [comment]
> Bloke will reverse the order on those for sake of logic

Please note that both settings are not interdependent and therefore there is not inherent logic order among them. Reversing the order of these settings would eventually satisfy a "cargo cult" mentality w/o any technical background in support of this change.

> Automatically adjust DST setting?

This setting determines whether the server should __automatically__ switch between DST and standard time if the operating system and PHP configuration supports this automatism.

> DST enabled?

This setting determines whether Textpattern uses a DST time offset to calculate the time as. Its value is either determined by a manual publisher action, or by an automatic program logic as described above.

**Comment by wion** [comment]
No cargo cult, eh. That eliminates code worry, then, i guess. I'd still recommend making the label changes. So whatever pref sits first, it defines the DST acronym, and drop the word "setting", which is giving the impression a cult exists.

**Comment by philwareham** [comment]
I've made some of the recommendations listed here. I also agree that the 'permalink titles' label is a bit clunky, but that would be a programming change. So if you feel it important, then please open an issue in the Textpattern repo itself.
