### ISSUE TITLE
Users panel: "Privileges" column header

### ISSUE THREAD

**Issue by wion** [textpattern/textpacks#115]
The "Privileges" column header should be renamed to "Roles", because that's what is actually being displayed. Privileges are the more complex rights structure that each role has, which is the focus of this doc: http://docs.textpattern.io/administration/user-roles-and-privileges

**Comment by petecooper** [comment]
+1 to this.

**Comment by philwareham** [comment]
I've done this here in GitHub and also on RPC so it should be live for users now. I've also updated the pophelp file to reflect this change.
