### ISSUE TITLE
typo in en-gb.textpack?

### ISSUE THREAD

**Issue by stefano-buscaglia** [textpattern/textpacks#119]
hi,
in en-gb.textpack you use 2 times permalink and more times permlink (without "a"), 
is this a typo?  

have a nice day

Stefano

**Comment by philwareham** [comment]
Hi. The actual tag name in Textpattern is 'permlink' so I have recently changed the wording to that, the string name will have to stay as 'permalink' because that is what the RPC system looks for when fetching text strings,

**Comment by petecooper** [comment]
Hi @stefano-buscaglia - to add to @philwareham's comments: you are correct when you say `permalink` and `permlink` are used in the Textpattern string name.

Both words mean the same. The confusion perhaps comes from different developers over the past years using different short terms for 'permanent link'.

Although personally I don't like the word `permalink`, it is a recognised term:
* https://en.wikipedia.org/wiki/Permalink (English language) 
* https://translate.google.com/translate?sl=en&tl=it&js=y&prev=_t&hl=en&ie=UTF-8&u=http%3A%2F%2Fen.wikipedia.org%2Fwiki%2FPermalink&edit-text= (lingua Italiano)

I think `permlink` was the original term used in early days of Textpattern.

**Comment by philwareham** [comment]
Hi all, I actually had a rethink on that a few days back and reverted to 'permalink'. Sorry for any confusion caused.

**Comment by petecooper** [comment]
![shakes fist](http://media.giphy.com/media/pEP4CwhG1f1uw/giphy.gif)

**Comment by stefano-buscaglia** [comment]
well that say (and see too)  :)
i think we can close this issue

have a nice day

S.
