### ISSUE TITLE
Clicking and tapping

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpacks#126]
I notice on two occasions (`password_reset_confirmation` and `press_preview_then_submit`) that the en-gb translations make reference to the actions 'click and tap'. Do we really need to spell it out? Or can they be reworded, e.g:

    Please confirm this reset request by [following|using|opening|...] the link below

Not everyone clicks and taps... right? Or is this just nitpicky?

**Comment by philwareham** [comment]
+1

I'm not too keen on the click and tap reference either.
