### ISSUE TITLE
Salutation refinement

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpacks#127]
The language string `greeting` is poorly implemented imo. In the code we append the person's name/realname to the greeting opener (`Dear` in English) and then add a comma by hand. This is not very RTL friendly.

Propose one of two changes, both here and in the core:

* Change `greeting` to be `Dear {name},` and amend the code to pass the name in to `gTxt()` (has backwards compatibility implications), or
* Add a new string, e.g. `salutation` defined as above, and change core to use it. Eventually drop `greeting` from whichever version bundles the Textpacks in the download.

State your preference/improvements. I'll own the core changes, whichever way we jump.

**Comment by philwareham** [comment]
@bloke I think the best course is to create the `salutation` string. The `greeting` string can simply be removed from standalone versioned Textpack files when we move to that planned format in 4.7.

**Comment by petecooper** [comment]
+1 for `salutation`, even though I think of Bill and Ted every time I hear it.

**Comment by petecooper** [comment]
A propos nothing, is there a list/log of strings that can be culled when the time comes?

**Comment by philwareham** [comment]
@petecooper issue #5 references that - though I would need to verify the ones in that initial list again and add any more that I find since that was raised.

**Comment by petecooper** [comment]
I see `salutation` has made it to the list of strings for 4.6 - I'll take dibs on adding, but I'll wait for confirmation from @Bloke that the code changes are done. Sound OK?

**Comment by Bloke** [comment]
[Done](https://github.com/textpattern/textpattern/commit/5cfe552a1a0bbd27a82e769c84803927e72887c9). Use `{name}` as the replacement string and include the comma:

    Dear {name},

    Be excellent to each other.

    Bill & Ted

**Comment by petecooper** [comment]
So, let me confirm for clarity: the string name is `salutation` and it uses `{name}`, like this -- taking en-gb as an example: `salutation => Dear {name},` -- right?

**Comment by Bloke** [comment]
Yup, spot on..

**Comment by petecooper** [comment]
All done, closing.
