### ISSUE TITLE
New strings: password alterations/strength

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpacks#133]
Bunch of new strings (sorry). This is just a placeholder issue right now, as the string names may alter in the next few days based on feedback from @philwareham on the password strength meter. But tentatively we have, in English:

* `password_strength` : "Strength:"
* `password_poor` : "poor"
* `password_weak` : "weak"
* `password_medium` : "medium"
* `password_strong` : "strong"
* `password_strongest` : "strongest"

And the following one goes in the body of the email sent to the user when their password has been changed via the new screen:

* `password_change_confirmation` : "Your password has been changed. If you did not authorize this change then please contact your Textpattern administrator."

(or something along those lines... maybe? Dunno how much detail to include here. But essentially it follows directly on from the `password_reset_confirmation` email, so should be in the same stylistic vein. It replaces the 'mail it to me' plaintext message).

I'm not sure on the names of the password strength levels yet. If we're going with 'poor', 'weak', and 'medium', maybe we should use 'password_good' and 'password_excellent' instead?

Also, `password_strength` is currently a separate entity with no replacement for the value. That's fine up to a point but it introduces a possible localisation issue as it could do with a space at the end of the string so it renders:

    Strength: poor

Spaces at the end of `gTxt()` strings are likely to get swallowed if strings are trimmed. The other alternative is to put the space in manually (in code) but that's not very RTL friendly. A third option is to add a parameter so the `password_strength` definition is:

    Strength: {strength}

But since each of the possible strengths need localisation too, that means yucky code that has a `gTxt()` inside a `gTxt()`. Not the end of the world, granted.

Finally, we could ditch `password_strength` entirely and just go with the five strengths and repeat the prefix:

* `password_poor` : "Strength: poor"
* `password_weak` : "Strength: weak"
* `password_medium` : "Strength: medium"
* ...

Not very DRY. But save a string, save the world.

Any advice / improvements appreciated.

**Comment by Bloke** [comment]
OK, [ditched the `password_strength` string](https://github.com/textpattern/textpattern/commit/3286d90353b6fd65101d04900118ad8690a5b3b8) and renamed the last two levels so we currently need these strings:

* `password_poor` : "Strength: poor"
* `password_weak` : "Strength: weak"
* `password_medium` : "Strength: medium"
* `password_good` : "Strength: good"
* `password_excellent` : "Strength: excellent"

plus the one that gets sent via email on password change.

Final answer, or any improvements yet?

**Comment by phiw13** [comment]
`password_excellent` : "Strength: excellent" --> `password_strong` : "Strength: strong" ?

I seriously doubt this pw: `asdf789erty` is really *excellent* (which is what your script claims it is). No need to give a too optimistic set of expectations.

**Comment by Bloke** [comment]
Hehe, so what would you suggest?

**Comment by philwareham** [comment]
Google uses:

Too short (although that is not really accurate) - 'Poor' would be better for us to use
Weak
Fair
Good
Strong

**Comment by Bloke** [comment]
Sounds good. I'll alter these as part of the next batch of updates when I tweak the javascript in the wake of your recent changes.

**Comment by phiw13** [comment]
@Bloke I suggested “strong”, I think ?

Apple Password utility rates it as moderate+ (~65% - light green)

PS - where is that repo?

**Comment by Bloke** [comment]
I'd say it was moderate too. Here's the [zxcvbn homepage](https://blogs.dropbox.com/tech/2012/04/zxcvbn-realistic-password-strength-estimation/) and its corresponding [github repo](https://github.com/dropbox/zxcvbn).

**Comment by Bloke** [comment]
@phiw13 Ah, Phil's just merged in a newer version of zxcvbn. Maybe that'll make a better job of that password you tried?

**Comment by philwareham** [comment]
Maybe. Best to use the latest version anyway.

**Comment by Bloke** [comment]
Thanks @philwareham for installing the latest version.

I've made those changes to the admin-layout-update branch now to keep the meter on-screen so it's back to you to alter the CSS class names for the umpteenth time, sorry.

**Comment by Bloke** [comment]
@phiw13 That pw you tried is only 'good' now under the new version of zxcvbn. An improvement.

**Comment by phiw13** [comment]
Yeah, I was just trying on their demo page, rating was ‘good’, more accurate me thinks. Testing on my localhost installs… Ok, “good” as well.

May we should have CSS classnames that aren’t tied to the values / strings…

**Comment by Bloke** [comment]
* `password_strength_0`
* `password_strength_1`
* `password_strength_2`
...

?

**Comment by philwareham** [comment]
Simple = better, so please do - and I will again change CSS ;)

**Comment by phiw13** [comment]
@Bloke 
Dunno, whatever makes it easy on your side. I prefer hyphens to underscores, though.

(it would stupid the have a TXP 4.6.x release with an update to that widget and force admin themes to update just because a simple classname change).

**Comment by Bloke** [comment]
You're right. Hyphens are better. Leave it with me.

**Comment by Bloke** [comment]
What about the `gTxt()` names? Are they better with number suffixes too, or should they stay with the more descriptive names?

**Comment by philwareham** [comment]
I think they would be better as number - that way if any new levels are added in the future we can add without the names tied to the strings.

**Comment by Bloke** [comment]
OK, please try that.

**Comment by philwareham** [comment]
Done from my side I think.

**Comment by philwareham** [comment]
Oh, the `.bar` classname seems to be missing, can you add it again?

**Comment by Bloke** [comment]
Nuts. I removed all class names instead of all bar `bar` (insert sheep-based nursery rhyme here). Hmmm...

**Comment by Bloke** [comment]
Done.

**Comment by petecooper** [comment]
That was dramatic. So, what was decided strings-wise?

**Comment by Bloke** [comment]
Final tally:

* `password_change_confirmation` : see OP.
* `password_strength_0` ('poor')
* `password_strength_1` ('weak')
* `password_strength_2` ('fair')
* `password_strength_3` ('good')
* `password_strength_4` ('strong')

**Comment by petecooper** [comment]
Strings added in the two commits preceding this comment. Unless I'm missing any todo, this can be closed.

**Comment by Bloke** [comment]
Close! We're not using the raw `password_strength` string any more, so it can be removed. It was deemed better to have each level be its own boss. This thread got a bit out of hand with my various dim-witted wranglings, sorry.

If you resync a dev copy to the latest admin-layout-update and visit `Admin->Users->Change password` you'll see the new strings pop up as you type. I'll leave it to your discretion whether the cooked strings appear as just the word corresponding to the strength of the password:
 
    [*******         ]
    Fair

or whether each of the five new strings requires a prefix to make it obvious:

    [*******         ]
    Strength: fair

I don't mind either way. I think people are probably savvy enough now to figure out what the former one means without being spoon-fed the prefix. Your call.

However, what does need adding is `password_change_confirmation`, which you'll only encounter if you do the following:

* Log out.
* Click `Forgot password` and send off your username.
* Follow link in email back to change password screen (note: button text and `show_password` are both unstringed too, sorry forgot to mention these, d'oh).
* Change your password.
* Read email confirmation stating password has been changed.

The body text of that final message is the string `password_change_confirmation` so it needs to have some sort of jolly message in a similar style to the `password_reset_confirmation` string. Whether we want to say that if they didn't authorise this change they should panic is again up to your discretion! Thanks.

BTW, the take-away learning outcome from this thread's debacle is that I'll no longer raise an issue here _prior_ to finishing the code but instead keep a local tally of any new strings as I develop a feature, then raise a new issue here when done, listing the strings. Saves everyone's sanity.

My box is beckoning, so I shall climb back in...

**Comment by petecooper** [comment]
I'll remove `password_strength` and replace with `password_change_confirmation`.

**Comment by petecooper** [comment]
@Bloke re: https://github.com/textpattern/textpacks/issues/133#issuecomment-155618437 -- you said button text and `show_password` are not yet stringed (unstrung) -- I opened https://github.com/textpattern/textpacks/issues/137 for `show_password`, can you open a new issue for the button text string when you have a moment, along with a short explanation if the above doesn't cover it. Thanks ever so.

**Comment by philwareham** [comment]
Done. I have had to duplicate the strings also in setup as they are needed there too (can't use common because the setup strings are included with installation).

Will need a minor change in core too.
