### ISSUE TITLE
Wall of text in `README.textile`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#134]
It's not welcoming, and a barrier to involvement -- especially so for non-English speaker.

I'll take this one on and clean it up, using this issue as a marker for now.
@wion -- I'd be grateful for your input if/when your schedule and workload permits.

**Comment by wion** [comment]
Assign it to me when you're done. I'll get to it eventually.

**Comment by petecooper** [comment]
GH design changes are imminent, will need to factor these in to revised text: https://github.com/blog/2085-a-new-look-for-repositories
