### ISSUE TITLE
New issues for new strings, please

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#135]
https://github.com/textpattern/textpacks/issues/113 is on the verge of becoming unwieldy. Rather than an ongoing list of strings, commits and edited comments we need to make it more modular.

I recommend that new strings have their own issue, either one issue per string or thematically-similar ones bunched together. This keeps it clean and manageable and avoids combing through threads.

@Bloke and @philwareham -- I'd be grateful if you could sprout a new issue for new strings, please. I'll keep combing through open issues just in case, but I'll be able to attend to stuff more quickly if it's in its own issue.

If you can both thumbs up this issue to say you're aware of it, I'll close. Thanks very much in advance.

**Comment by Bloke** [comment]
Will do. ::insert-thumbs-up-emoji-here::

**Comment by philwareham** [comment]
Let's close the original issue and then list those within in new issues then. I will see where we are at so far. Closing this.
