### ISSUE TITLE
Add password_confirm_button

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpacks#138]
Shown as the action button when setting a new password in response to a reset request. Screenshot:

![password_confirm_button](https://cloud.githubusercontent.com/assets/21252/11088953/049c4f56-885e-11e5-8757-d836ba3ab9b9.PNG)

Suggested text: `Set password` or something similar maybe?

**Comment by petecooper** [comment]
+1 for `Set password` -- I'll take this one.

**Comment by petecooper** [comment]
Done.
