### ISSUE TITLE
New strings: account activation

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpacks#144]
Eight new string names:

    login_sent_to
    set_password
    account_activation
    account_activation_confirmation
    password_set
    password_set_confirmation
    resend_activation
    resend_activation_request_sent

And here they are in context:

`login_sent_to` : replaces `password_sent_to`, and has an `{email}` replacement token in it.

`set_password` : has similar usage to `change_password`. Used on the Login page as page title and h1.

`account_activation`: Used in the subject line of the activation email:

    [$sitename] gTxt(account_activation)

`account_activation_confirmation`: a preamble to displaying the activation link. Similar to `password_reset_confirmation`, but for new accounts.

`password_set`: Used in the subject line of the email sent after you've successfully set the password on your brand new account:

    [$sitename] gTxt(password_set)

`password_set_confirmation`: The body of the message after you've successfully set the password for your new account. Similar in tone to `password_change_confirmation`.

`resend_activation`: Used as an action in the multi-edit option list.

`resend_activation_request_sent`: Message shown to admin users when resend_activation multi-edit has completed. A `{name}` replacement variable holds list of user names affected.

To see all the above in action, just add a new user using the admin-layout-update branch and follow the activation process through in a different browser / session (otherwise you'll just get logged back in when you click the activation link!)

**Comment by Bloke** [comment]
Just added two new strings to this issue to support [the resend activation commit](https://github.com/textpattern/textpattern/commit/afa1ec64b0ca38085e82cbd2f46c8f9b6f3bca92).

**Comment by petecooper** [comment]
@Bloke If you can dump the Brit version (or your closest approximation), I will happily take this and add placeholders for the other packs.

**Comment by rwetzlmayr** [comment]
@petecooper 
> add placeholders for the other packs.

You do know about https://github.com/textpattern/textpacks/blob/master/textpack, don't you?

**Comment by petecooper** [comment]
@rwetzlmayr I'll clarify. I meant I'll update the `en-*` packs with the string plus known translations, and update the non-English packs to include the `short_string_example =>` placeholder with a view to letting the translators fill in the blanks.

**Comment by Bloke** [comment]
@petecooper No probs, I'll attach a pack when I get a moment.

**Comment by Bloke** [comment]
First stab at en-gb pack [attached](https://github.com/textpattern/textpacks/files/48549/PasswordTextpack.txt).

**Comment by petecooper** [comment]
Strings added (see commits referenced above). Closing.

**Comment by philwareham** [comment]
I've added these into RPC now so please feel free to test the functionality out.

**Comment by Bloke** [comment]
Awesome job, guys. Thanks.
