### ISSUE TITLE
Link expiry indicator in token-related emails

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpacks#149]
Should there be an indication in emails sent out to authors regarding how long they have to respond? e.g.:

    You have been registered as a contributor to Death Star Weaponry
    Your login is: lord-vader
    Follow the link to activate your account and set a password:
    http://example.org/textpattern?activate=1234567890abcdef
    You have until {date time} to respond before this link expires.

We could add a `link_expires` string and tack it onto the emails for both registration and password reset requests. Or is it fine without the notification, so if someone inadvertently clicks the link after its expiry and enters a new password, they'll find the request is rejected without prior notification of this eventuality.

If we want the notifications, I'll add the two lines to core and put the string here for merging.

Thoughts?

**Comment by philwareham** [comment]
If it's relatively easy to code, then yes I think it would be beneficial.

**Comment by Bloke** [comment]
See [this commit](https://github.com/textpattern/textpattern/commit/b88976ce30bb3ead535ae8cf7a5faf2de2578a1c) which uses [this new string](https://github.com/textpattern/textpacks/files/50947/linkexpires.txt) to render its content:

    #@admin
    link_expires => You have until {when} to respond before this link expires.

The date format used (for now) is the one from your main prefs for _Date Format_. Bearing in mind that may omit the time portion, I wonder if we should just go with a fixed format here. But if so, which one satisfies all audiences and remains readable?

**Comment by philwareham** [comment]
hen you say 'fixed' I assume you still mean that it will be dynamically generated? If so, that that gets my vote.

**Comment by philwareham** [comment]
This is now in RPC server for you to test.

**Comment by Bloke** [comment]
Yes, a dynamically generated date, but represented in a hard-coded format. I just looked at the full range of available date formats and noticed that one of them is just the time, so the string would read a little odd!

I'm erring on the side of using this:

    You have until {Day MonthName, FullYear Hour:Min} to respond...

That's more British to put the day first, but I think we can get away with it because the month is spelled out so there's no confusion. And, the default installation is en-gb after all. Right?

**Comment by philwareham** [comment]
I think that is fine, because other languages can use a different combination in the string if they so wish. Let me know if agreed and I will amend the string in the repo and RPC. If you can also give me and idea of how that would look in en-us too I will amend that one as well.

**Comment by rwetzlmayr** [comment]
> That's more British to put the day first, but I think we can get away with it because the month is spelled out so there's no confusion

Strange idea. [There's an accepted international standard for writing dates.](https://en.wikipedia.org/wiki/ISO_8601)

**Comment by Bloke** [comment]
Yeah, standards eh?! It's just not very pretty in an otherwise friendly email to see ISO8601:

    You have until 2015-12-04T12:42 to respond before this link expires.

That's a bit like Robocop: You have 30 seconds to comply. Your move, creep :-)

**Comment by Bloke** [comment]
Instead of a fixed string like `{when}`, Phil's notion of being able to specify the parts per language is friendlier, albeit a bit cumbersome in the code and potentially in the string itself:

en-gb:
    You have until {day} {month}, {year} {hour} {minute} to respond before this link expires.

en-us:
    You have until {month} {day}, {year} {hour} {minute} to respond before this link expires.

And so forth... It's a bit more work for translators potentially, which I'd be keen to avoid, so if there's a KISS approach that satisfies readability over accuracy, I'd prefer that. But any approach is easily doable in code.

**Comment by rwetzlmayr** [comment]
> It's just not very pretty in an otherwise friendly email to see ISO8601

You may omit the 'T'. I think that's quite common. 

Using the British date/time format would render unusual punctuation for german-speaking cultures. We use "31. Dezember 2015" or 31. 12. 2015. See https://github.com/textpattern/textpattern/commit/553a43b93ebf1831a36e23eb8c4cbf270bf8b2ce for prior art ;)

**Comment by philwareham** [comment]
Couldn't the German translator us their own date pattern? The string is tied to language so you can have whatever format you like within it.

**Comment by rwetzlmayr** [comment]
Won't somebody please think of the French! And then [some more](https://en.m.wikipedia.org/wiki/Date_format_by_country).

I think it's either ISO, or delegate the task to the natives.

**Comment by Bloke** [comment]
OK, so British is out, thanks for the heads-up Robert. I don't mind delegating.

So, under the assumption that the time is pretty much universally represented using the colon and the 24-hour clock (because I can't find much evidence to the contrary, though haven't looked too much into RTL or non-Arabic numeral systems), and we're going to be passing Arabic numbers anyway, I'd expose these four values to the `link_expires` string:

    day
    month
    year
    time

In theory you can then use them in any order or manner you see fit in the string. I'll test it.

**Comment by Bloke** [comment]
OK, done. Works in German at least. Reports welcome, especially on the suitability of `%Oe` for the day.

**Comment by Bloke** [comment]
And here's the English string I used:

    #@admin
    link_expires => You have until {day} {month} {year}, {time} to respond before this link expires.

**Comment by philwareham** [comment]
Committed, and amended in RPC as well.
