### ISSUE TITLE
Search-related strings

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpacks#152]
Images panel search dropdown:

    extension => Extension

All search dropdowns:

    search_all => Search all

**Comment by philwareham** [comment]
Search all goes in common, yes?

**Comment by Bloke** [comment]
Erm, not sure. Wouldn't `admin` be better as I don't think it's used on the public side, and that's where common get loaded too.

**Comment by petecooper** [comment]
Done and done. Closing.

**Comment by philwareham** [comment]
I've always assumed 'admin' was the users panel and 'common' was for anything across the whole admin side (although also available to public side if they want). So in that case 'Search all' would be a common string.
