### ISSUE TITLE
Japanese textpack: 2 strings containing unnecessary markup

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpacks#174]
The translations for `is_dst` and `auto_dst` contain `<abbr></abbr>` markup. The markup is not needed (and actually incorrect - the string inside the markup is not an abbreviation…). IOW the text is correct, but there should be no markup.

twice : <abbr title="Daylight Saving Time">夏時間</abbr> --> 夏時間

Probably a relic of a galaxy long long time ago.

**Comment by philwareham** [comment]
Fixed, thanks. See https://github.com/textpattern/textpacks/pull/175#issuecomment-224828023.
