### ISSUE TITLE
Missing string for 'of'

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpacks#176]
It seems there are some changes with the nav_form() function (https://github.com/textpattern/textpattern/blob/master/textpattern/lib/txplib_html.php#L485) and the string used into the line #546 (https://github.com/textpattern/textpattern/blob/master/textpattern/lib/txplib_html.php#L546) isn't available for translators.

Previous versions of Textpattern used a different string for the current page indicator, and actualy this is "page" (https://github.com/textpattern/textpattern/blob/master/textpattern/lib/txplib_html.php#L533).

If I personnaly was in favor to use "page", the french community do not want, and prefer to keep "gabarit" as part of web pages. The problem is: "Gabarit 1 of 23" isn't relevant ("Model/Snippet 1 of 23" in English). 

IMHO "Results" may be more efficient for all languages (in use within the previous versions). So we could have: "Results 1 of 23" instead.

**Comment by philwareham** [comment]
So, if I understand correctly, the problem here is that the 'for' text isn't available for translation? If so, wouldn't it be better to do that instead of reverting the French word for page (gabarit) back to English? @Bloke might need to provide some assistance as I don't know of the 'for' is hardcoded or not.

**Comment by cara-tm** [comment]
I try: "Page" and it is fine in the context.
Sorry, that's not "for" but "of" and it is not hard coded (see: https://github.com/textpattern/textpattern/blob/master/textpattern/lib/txplib_html.php#L546)

**Comment by cara-tm** [comment]
;)
