### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpacks#180]
I can't understand.
When I upload a local fr-fr.txt file, I've got the right translation for "Page" (previously "Gabarit"); when I update the translation from the remote server, I do not get the expected results.

![failure](https://cloud.githubusercontent.com/assets/61045/16301794/a6a654c8-3947-11e6-8338-7c22c0310665.png)
![better](https://cloud.githubusercontent.com/assets/61045/16301798/ad6287a0-3947-11e6-84de-d92cc57071c2.png)

**Comment by philwareham** [comment]
Its is because I hadn't updated the RPC server yet - please try now and it will work.

**Comment by cara-tm** [comment]
Yep, fine!
Thank you.
