### ISSUE TITLE
recent_comments text string is missing(?)

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpacks#197]
Needed in tagbuilder

**Comment by philwareham** [comment]
It's already there: https://github.com/textpattern/textpacks/blob/master/textpacks/en-gb.txt#L1251

Display's fine in tag builder for me (in en-GB). Can you confirm?

**Comment by bloatware** [comment]
Nope. When I click "Recent comments" (pulled from `tag_recent_comments` string) tag builder link, I get `<txp:recent_comments label="recent_comments" />`. The default label here is `recent_comments` string (missing), not `tag_recent_comments`.

**Comment by philwareham** [comment]
OK  will add, thanks.

**Comment by Bloke** [comment]
It should be `tag_recent_comments` in the code, surely? All the other tag-specific ones are.

**Comment by bloatware** [comment]
They should, but they are not. Only builder links are populated from `tag_` strings, not the default attributes. I can change this, but are we sure that all `tag` strings will be ok on the public side?

**Comment by Bloke** [comment]
In which case, the default attribute for `tag_related_articles` should just be `related_articles`, which would require _another_ string.

As it only appears to affect these two tags, can we just assume that the label for the tag in the list is the same as the text in the default attribute and make them both use the `tag_` prefixed versions? Saves translation effort this close to release. And if the tag builder somehow gets moved to the docs (see http://forum.textpattern.com/viewtopic.php?pid=301033#p301033) or we move towards using txptag.org for tags docs, it's fewer unnecessary strings floating around.

But if I've missed something, then go ahead and create one or both strings.

**Comment by bloatware** [comment]
> In which case, the default attribute for `tag_related_articles` should just be `related_articles`, which would require another string.

It is, and `related_articles` is already present. We can not entirely switch to `tag_` in attributes, unfortunately. For example, `search` string is used as default label for Search input tag, but there is no `tag_search` string. But I can replace `recent_comments` with `tag_recent_comments` to avoid an extra string.

**Comment by philwareham** [comment]
The correct thing to do is create 2 new strings for `recent_comments ` and `related_articles`, which I will do. There won't be translation needed since I can duplicate the current translation texts for those (where they have already been translated). Public side shouldn't (and can't as far as I'm aware) hook into tag section text strings.

For discussion at another time: Why would we offload part of our documentation to a third-party site we have no control over and can't guarantee will stay live?

**Comment by bloatware** [comment]
>  Public side shouldn't (and can't as far as I'm aware) hook into tag section text strings.

I would merely split public/common and admin strings into two db tables. Currently loading language strings yields the heaviest db query on the public side.

**Comment by philwareham** [comment]
> I would merely split public/common and admin strings into two db tables. Currently loading language strings yields the heaviest db query on the public side.

Sounds like a good idea for Textpattern 4.7. Note that we also want to bundle all Textpacks and Pophelps (inline help files) with the installation instead of on the RPC server. We could even use XML for this (since that is what is output as default from Crowdin) if you think that has advantages.

**Comment by philwareham** [comment]
I've done this in RPC - just need to update the repo files later.

**Comment by Bloke** [comment]
> Why would we offload part of our documentation to a third-party site we have no control over and can't guarantee will stay live?

I erroneously thought we owned that domain. As you were.

**Comment by philwareham** [comment]
Done in 4.6.x branch. When I next sync the branches this will carry over. Closing.
