### ISSUE TITLE
Missing strings in base language

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#200]
I don't seem to be able to add missing strings to the base language in CrowdIn, so should I add them via fork+PR here, or is there another preferred route at CrowdIn?

**Comment by philwareham** [comment]
Hi. I've set up a sync between `crowdin-sync -> en-GB -> textpack.xml` - so if you add the missing strings in that file then they are added to Crowdin.

**Comment by petecooper** [comment]
Perfect - will deal.
