### ISSUE TITLE
GMT offset string reused

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#206]
I added some explanatory text to `gmtoffset` in commit https://github.com/textpattern/textpacks/commit/dd81fe9c02f4412daf290d39ee7781de2e864c48 and it works fine in Diagnostics where no geographical region is defined but the time offset is (Digital Ocean Ubuntu, I'm looking at you).

I've just spotted that the timezone in Admin -> Preferences uses `gmtoffset` as the gTxt, but doesn't actually state the offset in seconds, just the timezone from a loooong dropdown.

What's the best way to resolve this?:

* add another gTxt for the Admin -> Preferences area (this is my current preferred choice)
* actually show the GMT offset (yuck)
* revert the commit above (this will leave a bracketed number in Diagnostics where timezone doesn't have a name assigned)
* something else

Sorry I didn't spot this earlier.

**Comment by Bloke** [comment]
New string makes sense. Or relabel the old one again when we bundle the string with the download, as we then won't have any historical reliance on the strings with other versions.

**Comment by petecooper** [comment]
I'll shoot for a new string - relabelling/renaming just adds complexity, whereas a new string just makes more work for translators.

**Comment by petecooper** [comment]
OK, I'm leaning toward `tz_timezone` as it refers to the tz database [1], isn't too vague like `timezone`, and isn't too specific like `admin_prefs_server_timezone_from_tz_database_etc`.

Second brain requested - does that sound OK, @Bloke / @philwareham  / @bloatware ?

[1] https://en.wikipedia.org/wiki/Tz_database

**Comment by philwareham** [comment]
Sounds fine to me

**Comment by petecooper** [comment]
New string added via https://github.com/textpattern/textpacks/commit/939712e50bfbc3ba554a38a896051d6af2a79824 https://github.com/textpattern/textpacks/commit/d650b1049d803da763061d8d559722a245c13142 https://github.com/textpattern/textpacks/commit/303f1c14e7740a061ef00dbb9998d76c0787287a

**Comment by petecooper** [comment]
There's a function in `txp_prefs.php` that refers to `gmtoffset` in the `pluggable_ui` context:

```
/**
 * Renders a HTML &lt;select&gt; list of cities for timezone selection.
 *
 * Can be altered by plugins via the 'prefs_ui > gmtoffset'
 * pluggable UI callback event.
 *
 * @param  string $name HTML name of the list
 * @param  string $val  Initial (or current) selected option
 * @return string HTML
 */

function gmtoffset_select($name, $val)
{
    // Fetch *hidden* pref
    $key = get_pref('timezone_key', '', true);

    if ($key === '') {
        $key = (string) Txp::get('\Textpattern\Date\Timezone')->getTimezone();
    }

    $tz = new timezone;
    $ui = $tz->selectInput('timezone_key', $key, false, '', 'gmtoffset');

    return pluggable_ui('prefs_ui', 'gmtoffset', $ui, $name, $val);
}
```

In the spirit of not breaking plugins & things, I'd like to clarify -- is this the instance of `gmtoffset` that needs changing to `tz_timezone` to _only_ affect the HTML output, or is it elsewhere?:

```
    $ui = $tz->selectInput('timezone_key', $key, false, '', 'gmtoffset');
```

I think this is a @Bloke or @bloatware question. I'd appreciate clarification at a convenient time -- thanks.

**Comment by bloatware** [comment]
This instance of `gmtoffset` is the HTML `id` of the timezone select box. Changing it to something else could potentially break CSS rules or JS selectors in plugins. Is it a problem to leave it as is?

**Comment by petecooper** [comment]
>Is it a problem to leave it as is?

Bluntly, no. I spotted that the usage of `gmtoffset` wasn't very helpful in Diagnostics when the timezone isn't explicitly advertised by the server (e.g. Ubuntu on Digital Ocean), and there was just a number of seconds in brackets to indicate the GMT offset.

I can unpick the Textpack changes and set it back so Diagnostics is exactly as it was a month or so ago, no big deal. Should have some time for that later today

**Comment by bloatware** [comment]
No, I mean leave as is `gmtoffset` in
```
$ui = $tz->selectInput('timezone_key', $key, false, '', 'gmtoffset');
```
The rest of changes should be ok, though I don't quite understand the Diagnostics issue.

**Comment by petecooper** [comment]
>I don't quite understand the Diagnostics issue.

That I _can_ help with! First block of Diagnostics, note the output of `gmtoffset` and the value in parentheses:

```
Textpattern version: 4.6.2 (8412e32468526e075446b881d13bd9ce)
Last update: 1970-01-01 00:00:00/2016-11-29 08:00:02
Document root: /var/www/vhosts/textpattern.co/release-demo/live
$path_to_site: /var/www/vhosts/textpattern.co/release-demo/live
Textpattern path: /var/www/vhosts/textpattern.co/release-demo/live/textpattern
Article URL pattern: section_id_title
Temporary directory path: /tmp
Site URL: release-demo.textpattern.co
PHP version: 5.5.9-1ubuntu4.20
GD Graphics Library: 2.1.1-dev; supported formats: GIF, JPG, PNG.
Server TZ: America/Los_Angeles
Server local time: 2016-11-29 01:53:45
Daylight Saving Time enabled?: 0
Automatically adjust Daylight Saving Time setting?: 0
Time zone (GMT offset in seconds):  (-25200)
MySQL: 5.6.32-78.1
Database server time: 2016-11-29 01:53:45
Database server time offset: 1 s
Database server timezone: SYSTEM
Database session timezone: SYSTEM
Locale: en_GB.UTF-8
Server: Apache/2.4.7 (Ubuntu)
Apache version: Apache/2.4.7 (Ubuntu)
PHP server API: apache2handler
RFC 2616 headers: 
Server OS: Linux 4.4.0-45-generic
Admin-side theme: hive 4.6.2
```

Now see the attached Prefs excerpt, and note the output of `gmtoffset` -- the offset part is no longer relevant.

![safariscreensnapz003](https://cloud.githubusercontent.com/assets/226578/20705298/50b335d6-b61a-11e6-87ca-54901c593721.png)

My rationale was to make the Diagnostics more friendly (indicating what the number means) and I didn't catch the reuse of `gmtoffset` in Prefs. Whoops.

The solution (in the sense that I've now committed to this so I should finish or revert) is to add a gTxt for _just_ the TZ[1] timezone in prefs that doesn't mention the offset…because the TZ location doesn't mention it.

I hope this helps.

[1] https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by philwareham** [comment]
I think the solution is to leave the older translation of `gmtoffset` in place (which is used for prefs) and use the new `tz_timezone` on the diagnostics panel only (and mention '(GMT offset in seconds)' on that string instead).

**Comment by bloatware** [comment]
Ah, ok, thanks. We can also output (GMT offset in seconds) value in prefs select (like `Paris (3600)`), if it helps.

**Comment by philwareham** [comment]
@bloatware hmmm yes, that would save an additional language string, so perhaps that is the best solution.

**Comment by Bloke** [comment]
Ummm, related techie note: why are we using the deprecated `timezone` class from `txplib_misc.php` in the `gmtoffset_select()` function of `txp_prefs.php`?

**Comment by bloatware** [comment]
@Bloke Dunno, I'm new here :-) Please do what you deem necessary.

**Comment by Bloke** [comment]
Rats, that part of the code is a mystery to me. Was hoping you might have a clue :-)

Presumably, we should add the select list building method to the existing `\Textpattern\Date\Timezone.php` file. The other four functions have direct analogues in the namespaced class already, and are now simply stubs. Guess the select list builder just got left behind by mistake.

I'll figure it out.

**Comment by Bloke** [comment]
Okay, [try this](https://github.com/textpattern/textpattern/commit/9ff764c3923cdf6df5230c4609185adc8ac40817). It's not very pretty though. Perhaps we should omit any offsets that are 0, since they're the same as GMT. But that 'breaks' the label for those entries.  Dunno.

**Comment by bloatware** [comment]
Umm... sorry, on second thoughts, `selectInput()` looks strange in generic `\Textpattern\Date\Timezone` class.

**Comment by Bloke** [comment]
Yeah, I know what you mean. How do we separate functionality/display here? Should we have a dedicated `timezoneSelectInput()` in `txplib_forms.php`?

**Comment by bloatware** [comment]
Yeah, zactly. Probably, we need to somehow enhance generic `selectInput()` with `optgroup`, but I see no evident solution. Anyway, `txplib_forms.php` looks like a better place for it.

**Comment by Bloke** [comment]
[Better](https://github.com/textpattern/textpattern/commit/00379d8a69bdf589fbb7763f49d2c01e6eed5dd0)?

**Comment by bloatware** [comment]
Better! And maybe one day we'll refactor them and wrap in some `\Textpattern\Form` class.

**Comment by petecooper** [comment]
Looks good to me - I'll close. Thanks, @Bloke!

**Comment by philwareham** [comment]
Not finished with this issue just yet! The `tz_timezone` string that was added is not used in the core right now. Two options:

1. Delete the `tz_timezone` string. Leave the seconds offset numbers in the dropdown list in prefs.
2. Delete the seconds offset numbers in the dropdown list in prefs, use the string `tz_tmezone` for this pref and  then use `gmtoffset` in the diagnostics area only.

Let me know which route you want to go down.

**Comment by petecooper** [comment]
Sorry, @philwareham!

**Comment by petecooper** [comment]
Revisiting this -- if it's still relevant, I vote for option 2 on https://github.com/textpattern/textpacks/issues/206#issuecomment-266383612

**Comment by philwareham** [comment]
@Bloke Hi Stef, can you possibly amend the time zone pref in Textpattern so it uses the `tz_timezone` language string and also remove the seconds values from each `<option>`. I can then close this issue here.

I loked at the code myself but was unsure how it all functions, sorry!

**Comment by Bloke** [comment]
Removing the offset in the prefs panel dropdown is easy but I've had to put an exception in for the label, because the string it uses is tied to the pref name/html callback itself. But right now, there's no tz_timezone string I can see in the en-gb.txt or RPC so it renders the raw string on the prefs panel. What am I missing?

**Comment by philwareham** [comment]
@Bloke yes the `tz_timezone` string only exists in the languages branch files at the moment (and here on the Textpacks repo). I could put it in RPC but since this is 4.7 only I'd rather not.

**Comment by Bloke** [comment]
D'oh of course. Should I push this change to the languages-inclusion branch only then?

**Comment by philwareham** [comment]
Sounds reasonable - that branch will eventually go into dev so yes please!

**Comment by Bloke** [comment]
Okay, done.

**Comment by philwareham** [comment]
Thanks! Closing issue.
