### ISSUE TITLE
Missing string: section_delete_failure

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpacks#216]
Needs adding, for the times when you try to delete a bunch of sections via multi-edit, some of which contain articles and thus cannot be deleted.

The string contains one replacement parameter `{name}` that contains a list of sections that could not be deleted.

**Comment by petecooper** [comment]
So, something like this for English, @Bloke ?:

```
section_delete_failure -> Could not delete section(s), articles are currently assigned: {name}.
```

**Comment by Bloke** [comment]
Aye, something along those lines, thanks.

**Comment by petecooper** [comment]
Done. Closing.
