### ISSUE TITLE
Audit strings to common (and public)

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpacks#233]
There are strings that have common/public value that are currently buried in other groups. A good example being...

```
install => Install
```

...which currently resides in the `#@plugin` group.

We should ideally move as many of these to either the common group or public group depending on their relevance. @bloke is there any performance impact of a string being in common as opposed to another group?

To move to common:

- [ ] `high`
- [ ] `low`
- [ ] `show`
- [ ] `file`
- [ ] `install`
- [ ] `order`
- [ ] `language`
- [ ] `up_to_date`
- [ ] `section`
- [ ] `sections`
- [ ] `format`
- [ ] `random`
- [ ] `sort`
- [ ] `tag`
- [ ] `tags`

**Comment by petecooper** [comment]
I can do some librarian-ing on this @philwareham - OK for me to proceed?

**Comment by philwareham** [comment]
Yes please :). I also seem to have broken Travis again (if you go to tracks snd scroll to bottom of build there’ll be a reason why). Sorry I’ve had to pop out of house now otherwise I’d do it.

**Comment by petecooper** [comment]
No sweat - already on Travis stuff.

**Comment by Bloke** [comment]
Yes there's a small performance hit insofar as `common` strings are all loaded on the public side. So it increases the memory footprint of the public site.

We have:

* `public` for those that appear solely on the front side.
* `common` for those that be used both on the front side and admin side.
* other events / plugin names for those that can be used on the admin side.

Splitting them into where they appear on the admin side is more challenging than I thought because I think some are used in multiple places. Maybe we should make another group for those? Things like the multi-edit tool and list options, or table column names. But it's moot in terms of performance, unless we can determine the panel right at the start of the page load cycle. Handy for organisation purposes though so we can find strings more easily.

**Comment by petecooper** [comment]
OK, I'll hold off on re-org for now. I'm fine-tuning a Perl one-liner to move within a file, so I'll come back to this another time.

**Comment by philwareham** [comment]
Closing this, as I didn't realise that all strings are read in admin side, regardless of what group they are in. So even though `install` is buried in specific (`plugin`) group, all parts of the admin area can use that string.

Common and Public are read on the public side, and every new string we put in those impacts performance a teeny weeny bit.

**Comment by Bloke** [comment]
Yes. One option is:

* **public** for public-facing strings.
* **common** for strings that are required by both public- and admin-sides.
* **admin-side** for generic strings that are shared across admin panels.
* **_panel name_** for strings that are only applicable to that panel.

Then if we shunt all the strings around to fit into those groups, we can move towards loading only:

common + admin-side + panel + plugin strings targeted to any of the above groups

on each individual panel. A big memory saving.

**Comment by philwareham** [comment]
How viable is that to code in? I've just uploaded the INI file to Crowdin in the standard groups we had at 4.6. I *should* be able to regroup them without destroying the current translations. Since there are so many language upheavals at 4.7 I'd rather all big structural changes are done now rather than again at 4.8 or later. Cheers dude!

**Comment by Bloke** [comment]
In theory it's not super tricky and in fact may benefit us all round. If you take a look at the first few points in [this post](https://forum.textpattern.io/viewtopic.php?pid=307982#p307982) you'll see that the very first thing Txp does is load *all* the lang strings in the site's public language (not admin language). Clearly, that's not very efficient.

If we were to split up the strings properly, we could get away with loading just the common + admin-side + txp_auth strings here in the Public language. Then, if we have to render the login page, we're sorted. If however the person's logged in, we won't have wasted a tonne of memory loading everything.

Next, we find the user, look at what panel they're on, load the plugins, then load the *admin* strings for common + admin-side + current panel.

In theory it's not a huge undertaking for the code. Just change a few queries to alter the WHERE clauses to pull out strings from certian groups. The biggest thing will be refactoring the `en` language file + one other as a test into the relevant groups, with the possibility that all the work might be for nought if it doesn't work out.

**Comment by philwareham** [comment]
I can refactor 2 language files if necessary. I guess I would just use my common sense as to what constitutes a specific 'panel name' string and what an 'admin-side', 'common'?

**Comment by Bloke** [comment]
Absolutely. If you feel up to doing that, it'd be totally awesome and I'll see if I can get it working.

Basically, if the groups in the ini file match the `?event=` for specific pages, that's perfect. e.g.

* `[section]` for the Sections panel.
* `[css]` for the Styles panel.
* `[article]` for the Write panel.
* `[list]` for the Articles panel.
* ...

Anything that can be used on more than one panel goes in `[admin-side]`.
Anything that can be used on the public side as well, goes in `[common]`.
Anything that is only on the public side can go in `[public]`.

Things used for the likes of AJAX requests and JS-initiated messages will take some tinkering I expect and may end up in `[admin-side]` as some stuff we do from JavaScript works across panels.
