### ISSUE TITLE
Use `bdi` tag on LTR text within RTL languages

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpacks#234]
The `<bdi>` tag needs to wrap all instances of (non-code) LTR text present within RTL languages.

See:
https://www.w3.org/International/articles/inline-bidi-markup/
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/bdi

**Comment by petecooper** [comment]
https://travis-ci.org/textpattern/textpacks/builds/300190568

Travis is currently failing, appear to be on `bdi` inside `a` link `title` attribute:

```
textpattern_update_available => גירסה חדשה של מערכת <bdi dir="ltr">Textpattern</bdi> ({version}) <a href="https://textpattern.com/download" rel="external" title="הורד את מאיזור ההורדות של <bdi dir="ltr">Textpattern</bdi>">זמינה להורדה</a>.
```

**Comment by Bloke** [comment]
Does it work with apostrophes as one of the sets of quotes? Either the 'ltr' or the title attribute itself?

**Comment by petecooper** [comment]
I was wondering the same thing. Give me 5 minutes, and we'll know for sure…

**Comment by philwareham** [comment]
Please remove the title attribute - it’s refudindsnt anyway.

**Comment by philwareham** [comment]
Redundant, I mean!

**Comment by petecooper** [comment]
Green light: https://travis-ci.org/textpattern/textpacks/builds/300372522

**Comment by philwareham** [comment]
Thanks Pete!
