### ISSUE TITLE
Add a README for `tools/check-textpack.php`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#235]
I added `tools/check-textpack.php` in https://github.com/textpattern/textpacks/commit/f43a61f1f64064fe9150dcd0f9cc79895d19b99d because it's useful, but it still needs a README.

**Comment by petecooper** [comment]
@Bloke - I should have asked earlier and jumped the gun:

* are you OK with `check-textpack.php` being merged here?
* are you OK with it inheriting GPLv2?

Thanks!

**Comment by Bloke** [comment]
Sure, do what you like with it. Improve it if you can, it's a bit raw.

**Comment by petecooper** [comment]
Raw, but works. It was useful to me, hence inclusion.

Thanks very much!

**Comment by petecooper** [comment]
Boom, done.
