### ISSUE TITLE
Removing extraneous article timestamp gTxt strings

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#241]
About 4 days ago, I committed some additions after I noticed some missing gTxt strings in the dev branch. The gTxts have since been renamed (removed) in dev, and other strings have been used instead.

To that end, these are extra and I will remove:

- [ ] article_exp_day => Article expire day
- [ ] article_exp_hour => Article expire hour
- [ ] article_exp_minute => Article expire minute
- [ ] article_exp_month => Article expire month
- [ ] article_exp_second => Article expire second
- [ ] article_exp_year => Article expire year
- [ ] article_hour => Article hour
- [ ] article_minute => Article minute
- [ ] article_month => Article month
- [ ] article_second => Article second
- [ ] article_year => Article year

I'll close this issue when they're gone.

**Comment by philwareham** [comment]
Hi Pete, the whole master branch is going to be replaced with the ini-conversion branch in the next couple of days. So don’t worry.

I’ll probably need some help rewriting the old tests once the new structure is in place though.
