### ISSUE TITLE
What is 'pretext_data' string used for?

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpacks#242]
@bloke we have a language string that's been in the Textpattern codebase for years (but untranslated): `pretext_data` that I need to let translators know what it is/does so they can translate it. It's a diagnostic message but I can't figure out what exactly it is reporting. Can you shed some light on this?

**Comment by Bloke** [comment]
It's just used to output the result of the clean_url test in High Diagnostics. Presumably it'll help someone diagnose `.htaccess` issues.
