### ISSUE TITLE
Announce a drive to get strings updated on Crowdin for 4.7 release

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpacks#244]
Once I know what extra strings are needed to be added for the themes feature, and have put those strings into our [Crowdin project](http:translate.textpattern.io), we need to evangelise another push to get as many strings translated as we can before the final 4.7 release.

Via: Twitter, the forum, a blog post.

Also, post 4.7 release I will add the `en` pophelp to Crowdin too and encourage translators to start picking away at translating those items in native languages. The reason I'm holding back from doing that now is that: a) I don't have a final document of all the pophelps we will need for 4.7 yet, and b) I don't want to deter translators right now by suddenly throwing another ~120 documents for them to translate on top of the strings that are already in Crowdin. There is good momentum on Crowdin and I don't want to kill it by expecting another glut of work out of people.

**Comment by petecooper** [comment]
Standing by.

**Comment by philwareham** [comment]
Cheers dude!

**Comment by philwareham** [comment]
We can advertise/push the Crowdin site now for translators. I have regrouped all the strings on there now and reconfigured for our 4.7 `.ini` files. There will be a handful of additional strings to be added prior to 4.7 release, but those will just be appended to what's already on Crowdin.

**Comment by philwareham** [comment]
OK, I've written (and tweeted) a link to a new forum topic on this:

https://forum.textpattern.io/viewtopic.php?id=48274
