### ISSUE TITLE
More strings to add/remove

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpacks#246]
### Add to main Textpacks
- [x] enable_short_tags="Enable short tag support"

### Rename in main Textpacks
- [x] gd_unavailable -> unavailable
- [x] is_inaccessible -> path_inaccessible="<strong>{path}</strong> is not accessible."
- [x] upload_dir_perms -> directory_permissions="Check directory permissions: <strong>{path}</strong>."
- [x] skin_base_path -> skin_dir="Theme directory"

### Alter in main Textpacks
- [x] ago="{since} ago"
- [x] still_exists="<strong>{path}</strong> still exists."

### Add to `mode.ini`
- [x] ambiguous_tag_format = "Ambiguous tag format: <strong>{chunk}</strong>."
- [x] assert_array_value = "<strong>{name}</strong> is not an array."
- [x] assert_int_value = "<strong>{name}</strong> is not an integer."
- [x] assert_string_value = "<strong>{name}</strong> is not a string."
- [x] empty_partial_selector = "Empty selector for partial <strong>{name}</strong>."
- [x] field_not_found = "Field <strong>{name}</strong> not found."
- [x] form_circular_reference = "Too many nested form references while parsing form <strong>{name}</strong>."
- [x] invalid_pane = "Invalid pane."
- [x] mismatch_open_close_tag = "Tag opening/closing mismatch: {from}&hellip;{to}."
- [x] missing_close_tag = "Opening tag without corresponding closing tag: <strong>{chunk}</strong>."
- [x] missing_dom_extension = "PHP DOM extension unavailable."
- [x] missing_open_tag = "Closing tag without corresponding opening tag: <strong>{chunk}</strong>."
- [x] permlink_to_expired_article = "Attempt to link to expired article <strong>{id}</strong>."
- [x] plugin_include_error = "Unable to include plugin <strong>{$name}</strong>."

### Remove
- [x] per_page
- [x] linktext (in the [article] group)
- [x] already_exists
- [x] strong
- [x] path_to_site_inacc
- [x] update_still_exists
- [x] uploaded
- [x] delete_section_confirmation
- [x] edit_sections
- [x] time_ago

### Pophelp
- [x] Rename the pophelp entry `path_to_site_inacc` as `path_to_site_inaccessible`.
- [x] Rename `skin_base_path` as `skin_dir` and change text to reflect it's now a relative directory (like `img_dir`).

### Tag builder new strings required
- [x] depth="Depth"
- [x]  separator="Separator"

### Tag builder strings to delete:
- [x]  match="How are they related?"

### Move to [admin-side] group
- [x]  on_front_page

### Move to [common] group
- [x]  height="Height" (was `thumb_height`)
- [x]  width="Width" (was `thumb_width`)

**Comment by Bloke** [comment]
A few string changes noted in the OP regarding the tag builder. Can be done in lang-on-demand branch after the 4 remaining textpacks are regrouped (hr, nb, sr-rs, sr).

**Comment by philwareham** [comment]
@bloke OK, I've regrouped all the Crowdin languages now.

Looking at your requested string additions above... Does tag builder not have access to the other groups? If it does then:

1. We already have strings `thumb_height` and `thumb_width`which we could move to the `admin-side` (or`common`) group and make more generic `height` and `width`?
2. We have the `admin-side` string `parent` already.
3. We have the `admin-side` string `skin` (theme) already - can you not use that instead of a new `theme` string?
4. We already have string `on_front_page` which we could move to the `admin-side` group instead of a new `frontpage` string?

**Comment by Bloke** [comment]
Thanks for doing the lang regrouping. Sterling work, Sir.

I'd like to reuse strings where we can, for sure. I did all testing in dev NOT lang-on-demand so you're right that this list may actually be out of date. Let's give lang-on-demand a final test and merge it, then worry about if there are any tag builder bits remaining. I can rejig some of the strings it uses if they're in the `admin-side` or `common` groups (provided that the AJAX call to construct the tag builder uses them - I'll check).

**Comment by philwareham** [comment]
Righto. The regrouped Textpacks are in lang-on-demand branch for your testing.

**Comment by Bloke** [comment]
Couple more amendments noted. See https://github.com/textpattern/textpattern/commit/0115b0426a97b83a1867230540a2f0f4322295fb

**Comment by philwareham** [comment]
Done all these. Will leave issue open for now, in case other missing strings are found.
