### ISSUE TITLE
Skins strings to add

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#249]
- [x] `skin_count_css`
- [x] `skin_count_form`
- [x] `skin_count_page`
- [x] `skin_count_section`

Context:

![css](https://user-images.githubusercontent.com/226578/34321079-6d6cc298-e7fe-11e7-9ca9-6d364a706945.png)

![form](https://user-images.githubusercontent.com/226578/34321081-6f7b570c-e7fe-11e7-8ac0-92f26e77a039.png)

![page](https://user-images.githubusercontent.com/226578/34321082-71514a8c-e7fe-11e7-8e3f-b852e1931809.png)

![section](https://user-images.githubusercontent.com/226578/34321084-733c5922-e7fe-11e7-8d65-125a1e4299d6.png)

**Comment by petecooper** [comment]
@philwareham - shall I inject these or just leave them here as 'to be added'?

**Comment by philwareham** [comment]
Thanks Pete - I'll fix this when I do next Crowdin sync.

**Comment by philwareham** [comment]
@bloke Hi, can you please confirm that these translations would be correct (including the `{num}` bit too)? Cheers.

```
skin_count_css="Styles in this theme: {num}."
skin_count_form="Forms in this theme: {num}."
skin_count_page="Pages in this theme: {num}."
skin_count_section="Sections in this theme: {num}."
```

**Comment by petecooper** [comment]
Found another:

- [ ] `remove_extra_templates` – confirmation when exporting a theme.

![screen shot 2018-01-08 at 15 49 01](https://user-images.githubusercontent.com/226578/34678621-974eafa6-f48b-11e7-8010-94e188d8b28a.png)

**Comment by philwareham** [comment]
Bump?

**Comment by petecooper** [comment]
Tagging https://github.com/textpattern/pophelp/issues/42 for completeness

**Comment by Bloke** [comment]
Sorry, yeah the `skin_count_*` translations are perfect.

**Comment by philwareham** [comment]
This is done. Closing.
