### ISSUE TITLE
Capitalisation issue on Themes `With selected…` dropdown

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#250]
At `/textpattern/index.php?event=skin`, the `With selected…` dropdown has mixed caps case:

![screen shot 2017-12-23 at 16 30 08](https://user-images.githubusercontent.com/226578/34321092-c85502ba-e7fe-11e7-9954-462b02f78721.png)

(It strikes me this might be an issue for https://github.com/textpattern/textpattern and not https://github.com/textpattern/textpacks -- thoughts?)

**Comment by philwareham** [comment]
Strings for thenes hasn’t landed on core yet. You’re seeing the raw string.

**Comment by petecooper** [comment]
Aha! Thanks @philwareham.

**Comment by philwareham** [comment]
See Lang-on-demand branch for new text. Still quite a bit of Crowdin conversation to do before it’s ready.
