### ISSUE TITLE
`search_articles` not rendering in Articles panel

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#255]
Might need a re-order, as the `search_articles` exists already, but as of the current 4.7.0-dev it's not rendering. See top right search box.

![safariscreensnapz015](https://user-images.githubusercontent.com/226578/34998174-459f37ec-fad6-11e7-83be-099bdeb659ef.png)

**Comment by Bloke** [comment]
It's in the wrong group. Should be in `[list]` not `[articles]`.

**Comment by petecooper** [comment]
Good spot, @Bloke. @philwareham - shall I defer to you with CrowdIn stuff, or take this one?

**Comment by philwareham** [comment]
Every regrouped string means I need to reconfigure Crowdin - which is a bit of work. Best to create an issue that lists all the strings in wrong grouping so I can do it all in one hit.

I think there are also some additional text strings for multisite that @jools-r needs to send me, so again I can do this all at the same time.

**Comment by petecooper** [comment]
Alright, cool - I'll close this and start a CrowdIn batch issue instead.

(I'll send you some Monster Munch when all this is over…)

**Comment by petecooper** [comment]
Done: https://github.com/textpattern/textpacks/issues/256
