### ISSUE TITLE
3x `* is not writable` strings not rendering in Diagnostics panel

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#258]
I forced the themes, files and images directories to be non-writable, and the respective pre-flight messages don't appear to render properly from gTxt:

![safariscreensnapz001](https://user-images.githubusercontent.com/226578/35187953-4e49f33a-fe25-11e7-9efc-99c3cb7076e9.png)

Another moving task, I think. I will append https://github.com/textpattern/textpacks/issues/256 for CrowdIn

**Comment by Bloke** [comment]
Right. Those three need to be in the `[admin-side]` group, not just `[prefs]`. Nice find.

**Comment by petecooper** [comment]
Thanks, @Bloke - I've updated https://github.com/textpattern/textpacks/issues/256#issue-288970688 with the new destination.

**Comment by petecooper** [comment]
Gonna close this since https://github.com/textpattern/textpacks/issues/256#issue-288970688 shows the new destination and @philwareham can attend on the next CrowdIn run.
