### ISSUE TITLE
No mention of theme in `Change page/style`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#259]
When applying a theme to one or more sections, there's currently no reference to the theme element:

![re](https://user-images.githubusercontent.com/226578/35245565-a9e66f42-ffbb-11e7-918b-cbe7d4622cbd.png)

![screen shot 2018-01-22 at 21 32 26](https://user-images.githubusercontent.com/226578/35245625-d0a552c4-ffbb-11e7-8a5b-92d07bbf2764.png)

Proposal: change `change_page_style="Change page/style"` to `change_page_style="Change theme/page/style`

If approved, I'll update https://github.com/textpattern/textpacks/issues/256

**Comment by Bloke** [comment]
Good catch. Think it was just a holdover from when the theme wasn't part of the trio of selectors and I forgot to update the string.

**Comment by petecooper** [comment]
Updated https://github.com/textpattern/textpacks/issues/256, so closing.
