### ISSUE TITLE
Missing skin strings

### ISSUE THREAD

**Issue by NicolasGraph** [textpattern/textpacks#261]
Could you, please, add: `skin_not_found` (see https://github.com/NicolasGraph/textpattern/commit/6b4bce0963616f7c7cb83189a22bc7edfafce23e).
It works like `page_not_found`, `form_not_found` and `css_not_found`; it is displayed if, on duplication for example, Txp is unable to get the rows to duplicate (DB down or whatever).
We currently have `page_not_found="No page found for: <strong>{list}</strong>."` but maybe adding `data` like `page_not_found="No page data found for: <strong>{list}</strong>."` would be better.
Thus, for the new string, we would have: _No page data found for: theme_1, theme_2_.

**Comment by NicolasGraph** [comment]
I just read this, that is missing too: `skin_files_deletion_failed`.
I suggest `skin_files_deletion_failed="Skin files deletion failed for: <strong>{list}</strong>.` …I know, I'm good.

**Comment by philwareham** [comment]
@NicolasGraph and @Bloke - just want you to confirm the following string are the only missing strings related to the theme features now (so I don't have to reconfigure Crowdin again for 4.7.0 after this), and wording here is correct?...

- [ ] `skin_not_found="No theme data found for: <strong>{list}</strong>."`
- [ ] `skin_files_deletion_failed="Skin files deletion failed for: <strong>{list}</strong>."`

Cheers!

**Comment by NicolasGraph** [comment]
Let me take one more look to be sure… I'll come back later in the day.

**Comment by NicolasGraph** [comment]
Sorry, I forgot you while working on the Txp auto-install thing. I'll come back asap.

**Comment by NicolasGraph** [comment]
I'm going to feed this post with what I can find. I'll let you know when I won't find anything more to add.

- [ ] Change `form_type_error` to `form_subdir_error`
(could potentially be used by other assets in the future for other data than type)

`form_duplicate` is used with a _list_ parameter when some forms exists in several type related subfolders on import for now. We could add this item with a dedicated string telling that duplicates can't be imported, or if you think that it could be clear enough, just change `form_already_exists` to make it work with a list of names?

In progress…

**Comment by NicolasGraph** [comment]
Ok @philwareham, hopefully I didn't miss anything…

**Comment by NicolasGraph** [comment]
Sorry, I posted these strings into the future potential strings issue but they are needed on import/export when the `skin_synchronize` option is checked:

```
css_files_deletion_failed => Styles files deletion failed for: <strong>{$list}</strong>.
form_files_deletion_failed => Forms files deletion failed for: <strong>{$list}</strong>.
page_files_deletion_failed => Pages files deletion failed for: <strong>{$list}</strong>.
```

**Comment by NicolasGraph** [comment]
Thanks @philwareham!
