### ISSUE TITLE
`include_email_atom` and `use_mail_on_feeds_id` uniformity

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#268]
Raising here because I'm rusty at Crowdin.

`include_email_atom` states "Include email in Atom feeds?" and `use_mail_on_feeds_id` states "Use email address to construct feed ID (default is site URL)?"

`include_email_atom` should probably be extended to "Include email address in Atom feeds?" for uniformity.

**Comment by philwareham** [comment]
Done, thanks. Please note that any pophelp amends need to be submitted to the [pophelp repo](https://github.com/textpattern/pophelp).

**Comment by petecooper** [comment]
Aha! That makes more sense – I'll get onto that. Thanks for the pointer!
