### ISSUE TITLE
Move string: `problem_connecting_update_server`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#273]
I have a feeling `problem_connecting_update_server` is in the wrong place.

It should be moved to the `[diag]` section, not `[prefs]` as it most commonly (only? always) appears in the Diagnostics panel.

This might be a factor in the untranslated `problem_connecting_update_server` strings popping up now and again.

**Comment by Bloke** [comment]
Yes. Bug. Well spotted.

**Comment by Bloke** [comment]
Yes. Bug. Well spotted.

EDIT: The string itself also needs altering to remove reference to the RPC server.

**Comment by petecooper** [comment]
@philwareham - I don't want to knacker CrowdIn sync. What's the smoothest way for me to fix this without making a ton of work for you?

**Comment by philwareham** [comment]
@petecooper if you amend the en.ini files and en-gb.ini files in the Textpack repo - I can then import that change to Crowdin. I have to then manually generate each translation in Crowdin again but it keeps the old translated text in memory so it's not massive amounts of work.

**Comment by petecooper** [comment]
Thanks @philwareham. I've made the changes in `en.ini` and `en-gb.ini`, they can be slotted into CrowdIn as and when (not a showstopper).
