### ISSUE TITLE
Is the `4.6.x` branch still relevant?

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#274]
Per the title, is the 4.6.x branch still relevant? It appears to be set up for the legacy RPC server stuff and has been superseded by CrowdIn in master. Is it safe to delete?

**Comment by philwareham** [comment]
It might be of use to some people. Probably could delete it though for cleanliness.

**Comment by petecooper** [comment]
Cheers @philwareham. I'll poke around and see what the changes were post-fork, see what's what.
