### ISSUE TITLE
New strings in Textpattern 4.7.2

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#276]
`change_dev_page_style` and `switch_dev_live`

![screen shot 2018-10-02 at 14 34 06](https://user-images.githubusercontent.com/226578/46351856-4e693080-c650-11e8-9abf-8542d8202be8.png)

**Comment by philwareham** [comment]
@petecooper @bloatware So these should be?...

    change_dev_page_style="Change dev theme/page/style"
    switch_dev_live="Switch dev/live theme"
    dev_to_live="From dev to live"
    love_to_dev="From love to dev"

...or something else? Thanks.

**Comment by petecooper** [comment]
That would be along my best guess, but I'll defer to @bloatware.

**Comment by bloatware** [comment]
Yep, please, if it sounds clear. I thought we would collect all missing strings in a separate issue once things take their final shape.

**Comment by petecooper** [comment]
Adding `custom_form_types` from Preferences -> Advanced options.

![screen shot 2018-10-12 at 23 38 12](https://user-images.githubusercontent.com/226578/46897001-0e882180-ce78-11e8-8fa1-ee7611e81252.png)

**Comment by petecooper** [comment]
Context of `switch_dev_live`, `dev_to_live` and `live_to_dev` for completeness:

![screen shot 2018-10-24 at 11 54 38](https://user-images.githubusercontent.com/226578/47425934-b5779200-d783-11e8-9951-5f0b543babe8.png)

**Comment by bloatware** [comment]
Sorry guys, a late thought. We could probably transform `live_to_dev` and `dev_to_live` switches into checkboxes under `Change theme` and `Change dev theme` combos respectively. This looks easier to understand and spares `switch_dev_live` string. What do you think?

**Comment by Bloke** [comment]
Seems good. I was a bit confused by the option actually. It didn't seem to swap back for some reason after making a section live, but I suspect pebkac.

**Comment by philwareham** [comment]
So the texts start the same, we just delete the `switch_dev_live` string, yes?

**Comment by bloatware** [comment]
I've tried to combine all this under `Change theme/page/style` item. The idea is to use it for both live and dev themes switch, via a radio set. An additional checkbox would enable live/dev sync. It works well, but looks overcharged, improvements needed:

[![change-theme.png](https://i.postimg.cc/JnNWyQR8/change-theme.png)](https://postimg.cc/njhWgBsS)

**Comment by bloatware** [comment]
Re `switch_dev_live` option: its main purpose is to easily "publish" dev assets when ready. You just hit "switch to dev" and the dev theme becomes public. Without this option you'd need to choose and assign dev values to live assets (theme/page/style) section by section, as soon as dev and live differ enough. This seems useful, but I struggle with the terminology.

**Comment by philwareham** [comment]
@bloatware can you let me know where `txp_evaluate_functions` appears in the CMS control panel?

**Comment by bloatware** [comment]
In `Advanced options`. You must logout/login to create it.
