### ISSUE TITLE
RFC: trailing `.` after directory locations in diagnostics messages

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#281]
Where a string translation includes a directory location immediately before a trailing full stop, for example `path_creation_or_writing_failed`, `path_not_readable` and `path_not_writable`, said directory location is more copy & paste-able if there's no trailing full stop. We would lose the grammatical accuracy, but given it's a diagnostics message, the focus should be on resolving messages.

![Screen Shot 2019-09-24 at 18 32 01](https://user-images.githubusercontent.com/226578/65535573-a2bc8e80-def9-11e9-82dc-97cbd7e20d71.png)

Edit: I realise the screenshot doesn't relate to the examples I have, but the logic is sound.

**Comment by Bloke** [comment]
If we want to do this, it just requires a language string change for the key `dir_not_writable` to remove the trailing ful stop.

There may be other strings we wish to treat the same way on the diag panel (e.g. `site_trailing_slash`?)

**Comment by petecooper** [comment]
@Bloke - yep, I'm sure there are others strings lurking. It's more of a policy question, really – does usability (or copyandpasteability) trump grammar, at least in the case of messages?

**Comment by Bloke** [comment]
Consistency is nice, but usability for me has the edge.

**Comment by philwareham** [comment]
Done in all instances of diagnostics (English language files). Thanks.
