### ISSUE TITLE
Proposed change to 'List options' string

### ISSUE THREAD

**Issue by wion** [textpattern/textpacks#284]
One thing I noticed while editing [Common panel functionality](https://docs.textpattern.com/administration/common-panel-functionality), was the necessary use of (and subsequent necessary clarification of) 'list' and 'table', two semantically different things, to talk about the 'lists'/tables in panel main displays. Secondary features, like **List options** use the 'list' angle too, but at the same time it's necessary use 'column' or 'headers' when talking about sorting and toggling, and whatnot which are definitively table constructs.

To me it's a table, clearly, and to anybody, so table, columns, rows, cells, column headers... these are the terms to be using in strings, docs, and wherever else such features are written about or referred to.

I realize the concept is 'a list of {type items}', respective to panel, but I don't think it confuses anybody by saying 'the {type items} table' when in context of the panel, and especially since a table is what it is.

The related docs issue...
https://github.com/textpattern/textpattern.github.io/issues/132

**Comment by philwareham** [comment]
Technically I agree, they are - semantically - tables. However, I think a user would understand 'the article list' better as a reference than 'the article table', for example.

**Comment by wion** [comment]
I apologize for not being clear. Copy/pasting from the other issues was a bad idea.

The focus of this issue, when it gets down to it, is a single string: **List options** (I've corrected the subject line). Nothing else in the interface of the relevant panels uses the word 'list' to describe table handling features.

The label is problematic, IMO, because it's not clearly saying what the options are, thus the label fails its duty as a good label. A user has to click the link to discover it's about 'hiding/showing columns'. If they could see that from the surface, they might never need to click the link, or be better reminded that the ability is available to them. But as it is now, nothing is clear either way, a user must click to discover, and then they realize it's about _columns_ display, not records (as 'list' would imply)

So it seems to me this isn't about 'list' vs. 'table', but about making a better label based on what the function is really doing. Some possible good options would be:

* Hide/show columns
* Column display options

It's an extra word, but decisively more clear.

After that, it's easy to talk or write about it any way a person wants. In fact, they won't even need to because it's so obvious at that point, which _is_ the point of making such changes.

**Comment by philwareham** [comment]
Oh, I see what you mean now :) - done in English language files and linked to Crowdin (translators may wish to amend their wording too). Thanks Destry.
