### ISSUE TITLE
Missing string: skin_name_invalid

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpacks#287]
Required in `[skin]` area for times when you (for example) edit a current theme, blank out the name and hit 'Duplicate'.

Not vital for 4.8.0. Can defer to 4.8.1. In fact, there might be a better way to handle this altogether so we may not even need this string, but let's leave it here as a reminder to check this out post-release.

**Comment by petecooper** [comment]
Bumping this since we're approaching 4.8.2.

**Comment by Bloke** [comment]
Good bump, thanks. We need to include this.

**Comment by philwareham** [comment]
Can you provide me some text for this, please?

**Comment by Bloke** [comment]
I think this should do it:

```
Theme name <strong>{name}</strong> invalid.
```

(although I've only managed to trigger it when `$name` is empty. But to be on the safe side, let's keep the` {name}` in there, as it'll still read okay if it's missing. Thanks!

**Comment by philwareham** [comment]
Dine, thanks. Closing.
