### ISSUE TITLE
Move `language` to `[common]` for login language selector

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#288]
https://forum.textpattern.com/viewtopic.php?pid=323874#p323874
https://forum.textpattern.com/viewtopic.php?pid=323879#p323879

New feature on login panel includes a dropdown, and it uses the existing `language` string:

![Screenshot 2020-06-21 at 17 44 26](https://user-images.githubusercontent.com/226578/85230261-e0960700-b3e6-11ea-92ca-b8157b1474ae.png)

Easiest solution seems to be to move `language` into the `[common]` section.

**Comment by Bloke** [comment]
We also need to move `active_language_ui` to `[admin-side]` so the selector on the Admin>Users>Edit panel renders properly.

**Comment by philwareham** [comment]
Done and done. Translators will gradually amend this in their own languages.
