### ISSUE TITLE
Comment images label and pophelp need altering

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpacks#290]
We have the logic backwards in core. Rename: `comments_disallow_images` label.

From `Strip commenter images from comments?`
To: `Allow commenter images in comments?`

Alter pophelp of the same name to reflect this change.

See https://forum.textpattern.com/viewtopic.php?id=50974.

**Comment by philwareham** [comment]
Looping in https://github.com/textpattern/textpattern/issues/1534 so we don't miss this
