### ISSUE TITLE
Missing string: `override_form_types`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#293]
See: https://github.com/textpattern/textpattern/issues/1553#issuecomment-736899723

`en` text to use: 

>Override form types

(Raising an issue since I don't want to break translation workflow.)

Please tag with `4.8.5` milestone (I can't).

**Comment by philwareham** [comment]
Seems I have used the wrong string name here (`allow_form_types`). Reopened.

**Comment by petecooper** [comment]
My fault. Apologies.
