### ISSUE TITLE
String changes: `password_sent_to` and `login_sent_to`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#294]
We don't send plaintext passwords these days.

Suggested tweaks:
* `login_sent_to="Login details sent to {email}."`
* `password_sent_to="Login details sent to"`

**Comment by Bloke** [comment]
Absolutely. We might even be able to design out the 'password_sent_to' string and just use the login version.

**Comment by petecooper** [comment]
4.8.5 to change and 4.9.0 to design out?

**Comment by Bloke** [comment]
4.8.5 for both. It only occurs once in the code as far as grep is concermed.

**Comment by Bloke** [comment]
In fact, password_sent_to isn't even used any more: it's in a deprecated function that has been given the heave-ho since 4.6.0. So nothing to change in that string. Just remove it from all the lang packs and Crowdin as far as I'm concerned, and tweak the login_sent_to as you suggest.
