### ISSUE TITLE
Clarification on 'Reset password'

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#297]
![re](https://user-images.githubusercontent.com/226578/105725399-d1e57480-5f20-11eb-9a11-3acfe7983e68.png)

File under: UX. Admin &rarr; Users.

That ‘Reset password’ option implies I can change the password for someone else, it doesn’t mention that it should send an email that has the user change their own password.

Something like ’Send reset password link’ or similar would solve this, I think.

**Comment by Bloke** [comment]
I think the wording was a holdover from when we did actually send the new password out in plaintext. So yeah, a spruce-up would defintiely help to reflect the current functionality.

Good catch, thanks.

**Comment by philwareham** [comment]
Is this a 4.8.5 thing?

**Comment by petecooper** [comment]
I'm inclined to bump to 4.9 given its trivial nature.

**Comment by philwareham** [comment]
@Bloke @petecooper which string is this exactly? There are a few in the list with the same phrase. Ta.

**Comment by petecooper** [comment]
@philwareham – it looks like `resetpassword` according to https://github.com/textpattern/textpattern/blob/16863fae23a961a87e7b5c1a953da7f9cdd10f3b/textpattern/include/txp_admin.php#L745
