### ISSUE TITLE
Strings for SMTP mail support

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpacks#298]
A whole bunch of strings required. Tentative translations suggested below. Any improvements, please suggest/amend.

- [x] [common] `mail="Mail"`
- [x] [prefs] `enhanced_email ="Use enhanced mail features?"`
- [x] [prefs] `mail_enhanced ="Enhanced mail settings"`
- [x] [prefs] `smtp_host="SMTP host"`
- [x] [prefs] `smtp_pass="SMTP password"`
- [x] [prefs] `smtp_port="SMTP port"`
- [x] [prefs] `smtp_sectype="SMTP security method"`
- [x] [prefs] `smtp_user="SMTP user name"`

**Comment by philwareham** [comment]
Yep, saw this yesterday. I’ll give it another day of two to settle in, in case any changes happen, then add them in (and push to Crowdin).

**Comment by philwareham** [comment]
@Bloke can we use a consistent `mail_xxxx` for these strings if possible? That would then group them together in the prefs section for easier clarity. Let me know and I'll suggest alternative names for the above.

**Comment by Bloke** [comment]
Aye. Don't see why not. We can tweak the string names.

**Comment by philwareham** [comment]
@bloke please see above where I have edited the string names. Please adjust in your code (or let me know if any of my changes are not appropriate) - this is not in dev for testing.

Once I know you are happy with this, I'll sync into Crowding for translators to work on. Thanks!
