### ISSUE TITLE
Amend only_graphic_files_allowed to allow dynamic list of filetypes

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpacks#299]
See https://github.com/textpattern/textpattern/issues/922#issuecomment-781305701. @Bloke Just waiting for confirmation that this is going ahead.

**Comment by Bloke** [comment]
Nice one, thank you.

**Comment by philwareham** [comment]
I need to sort out some issues on Crowdin (syncing changes made in these repos recently back to them, as they are slightly out of sync) but that doesn't affect 4.8.5 directly.

If you can give me a rough estimate of when you are planning to release 4.8.5 I will try to get a handful of the extra translations that are on Crowdin into the repo (I can't any tonight though). Not a deal-breaker if those translations get missed out - but nice to add if time permits.
