### ISSUE TITLE
Resync Crowdin with latest Textpack and Pophelp changes from repos

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpacks#300]
NTS I need to fix a couple of sync issues I have with Crowdin, which means a handful of changes in the repos and Crowdin are at odds. Will try to fix for 4.8.5, but defo for 4.9.

**Comment by philwareham** [comment]
Done. More work than expected. NTS avoid moving strings in XML files as it breaks Crowdin.

**Comment by Bloke** [comment]
Oooft. Thanks for doing the grunt work here.
