### ISSUE TITLE
Consider refreshing text for `old_placeholder`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#302]
Background: https://github.com/textpattern/textpattern/issues/1656

tl:dr; subdirectories may be valid, current diags messaging is a bit misleading.

Not sure what best to revise it to – brain still warming up today – any suggestions?

**Comment by Bloke** [comment]
Since it's highlighting a name clash between a directory and a section, maybe:

> Section named the same as directory: {path}.

And for the pophelp:

> Existing directory files may conflict with section names used in the permlink scheme. To avoid issues, delete the clashing directory name(s) if it is safe to do so, or alter section names so they are different to the reported directories.

**Comment by petecooper** [comment]
>Although if you make a section called 'textpattern' I expect you'll have far bigger issues like a broken admin side.

Be right back…

**Comment by petecooper** [comment]
>Existing directory names may conflict with section names used in the article permlink scheme. To avoid issues, delete the clashing directory name(s) if it is safe to do so, or alter section name(s) so they do not clash with the corresponding section(s).

**Comment by philwareham** [comment]
OK, done. Please close if happy with it. I'll merge into Crowdin later today once closed here, so translators can do their thing.

**Comment by Bloke** [comment]
Woot! Lightning...

**Comment by petecooper** [comment]
![b651caa87c4b8326dde2f7d2755e1b7c](https://user-images.githubusercontent.com/226578/112142556-a6080780-8bce-11eb-80e8-c2694981553e.jpg)
