### ISSUE TITLE
Change `disk` to `file system` or similar

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#303]
Can we consider an alternative to `disk`? Maybe `file system` or `drive`? A similar term that's not so legacy as 'disk'.

Relatively few people refer to the physical things as 'hard disk drives' these days, they're 'hard drives'. Solid state drives and flash storage don't even use disks.

(I searched for a "bikeshedding" label, but thankfully there isn't one…)

**Comment by philwareham** [comment]
OK, seems fair. I'll do this in 4.9 cycle though.
