### ISSUE TITLE
Move unknown_section from mode.ini to regular lang

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpacks#309]
It seems we use `unknown_section` as a regular public side output string for those instances where you might configure a pageless section and then try to view an article directly assigned to it. At the moment, the translated string only shows up if the site is in debugging/testing mode.

**Comment by philwareham** [comment]
So, to `public` or `common` group?

**Comment by Bloke** [comment]
If we're going to keep using it for https://github.com/textpattern/textpattern/issues/1765 then it'll need to be in `common`. But if we're going to tweak the back-end to use `no_sections_available` then `public` is best because we won't be using it admin side.

**Comment by philwareham** [comment]
This was already done back in December 2021, so closing.
