### ISSUE TITLE
Add Sardinian (`sc`), offer of translation received

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpacks#315]
Via email:

>Dear Friends
is it possible to also introduce translation into the Sardinian language, a language of Sardinia that has been recognized by the Italian state through Law No. 482 of 1999?
I am willing to do the translation, being an expert in Sardinian language translation and terminology.

https://en.wikipedia.org/wiki/Sardinian_language

If someone can set up the scaffold, I'll handle the enquiry. Thanks!

**Comment by Bloke** [comment]
Excellent news. That takes us to 61 supported languages!

[Language placeholder added on CrowdIn](https://crowdin.com/project/textpattern-cms-textpacks/sc) which I think is everything that is required. As far as I'm aware, we can simply pull translation strings down into the Textpack repo from there, and then sync it across to dev. Fingers crossed.

**Comment by Bloke** [comment]
And [pophelp topics are available too, I think](https://crowdin.com/translate/textpattern-cms-textpacks/44/engb-sc?filter=basic&value=0)
